# Generated by Django 2.0.9 on 2018-10-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('dia', models.DateField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
